name: Flutter CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Create Android project
        run: |
          if [ ! -d android ]; then
            flutter create --platforms=android .
            rm -rf test
          fi

      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: |
            if [ -d test ]; then
              flutter test
            else
              echo "No test directory found. Skipping tests."
            fi
      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
         name: desafio-ctb-apk
         path: build/app/outputs/flutter-apk/app-debug.apk
